#branches:
#  only:
#    - master
sudo: false
language: php
php:
  - '5.6'
services:
  - mysql
  - elasticsearch
before_script:
  - mysql -e 'create database syrup;'
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install -n --no-scripts
  - echo "memory_limit=128M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - ./bin/phpcs --standard=psr2 -n src tests
#  - ./bin/phpmd src/ text codesize,unusedcode,naming,phpmd.xml
  - ./bin/phpunit --debug
after_script:
  - ./codeclimate.sh
notifications:
  slack:
    secure: I73TdwZCz04fIrLIM8kctaZd6uyVhqBZXs1L6wFC2lhyUFX+L5kxKRldOyBrQp1v5SL+wkuok+CBPmqxa1e75fWYA7Zsi/VpH+XFnG2zCjuq1+v9wXjiWMVp75aL24kcsm6WiXqqpEIrpnaO99+nXDuT9+Os/+0COW0wN1sfwjg=
