#branches:
#  only:
#    - master


sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build
script: docker-compose run --rm tests
after_success:
  - docker images
  - docker-compose run --rm --entrypoint=/code/codeclimate.sh tests
notifications:
  slack:
    secure: MeAoPVdt5CkfikRn0Qb382PW3IVxTmhioiS0VuGHBumDW88CwigQVCJZGfs9xeuZvOTZQEgxiLNrGVCqT1z7qaGfW7XVA2ir2Izqz8cSStwF4b+yTbVmHC5NFjoiEun9b1738061HEJU+vJI56TTViXAOrTolucsRrAQixUyQ4o=
  email: false
