imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

monolog:
    handlers:
        syrup_syslog:
            type: syslog
            ident: %app_name%
            level: debug
            channels: ["!request", "!event", "!doctrine"]
            formatter: syrup.monolog.formatter
        storage_api:
            type: service
            id: syrup.monolog.sapi_handler
            ident: %app_name%
            level: info
            channels: ["!request", "!event", "!doctrine"]
