services:
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%syrup.host%;dbname=%syrup.name%"
            - "%syrup.user%"
            - "%syrup.password%"
        calls:
            - [setAttribute, [3,2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    syrup.listener.exception:
        class: Keboola\Syrup\Listener\SyrupExceptionListener
        arguments: ["%app_name%", "@syrup.storage_api", "@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: console.exception, method: onConsoleException }

    syrup.listener.controller:
        class: Keboola\Syrup\Listener\SyrupControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    syrup.s3_uploader:
        class: Keboola\DebugLogUploader\UploaderS3
        arguments: ["%uploader%"]

    syrup.monolog.sapi_handler:
        class: Keboola\Syrup\Monolog\Handler\StorageApiHandler
        arguments: ["%app_name%", "@syrup.storage_api"]

    syrup.monolog.signal_handler:
        class: Keboola\Syrup\Monolog\Handler\SignalHandler

    syrup.monolog.syslog_processor:
        class: Keboola\Syrup\Monolog\Processor\SyslogProcessor
        arguments: ["%app_name%", "@syrup.storage_api", "@syrup.s3_uploader"]
        tags:
            - { name: monolog.processor, method: processRecord, handler: syrup_syslog }

    syrup.monolog.request_processor:
        class: Keboola\Syrup\Monolog\Processor\RequestProcessor
        arguments: ["@request_stack", "@syrup.s3_uploader"]
        tags:
            - { name: monolog.processor, method: processRecord }

    syrup.monolog.job_processor:
        class: Keboola\Syrup\Monolog\Processor\JobProcessor
        tags:
            - { name: monolog.processor, method: processRecord }

    syrup.monolog.formatter:
        class: Keboola\Syrup\Monolog\Formatter\JsonFormatter

    syrup.routing_loader:
        class: Keboola\Syrup\Routing\Loader
        arguments: ["%components%"]
        tags:
            - { name: routing.loader }

    syrup.temp:
        class: Keboola\Temp\Temp
        arguments: ["%app_name%"]

    syrup.storage_api:
        class: Keboola\Syrup\Service\StorageApi\StorageApiService
        arguments: ["@request_stack", "%storage_api.url%"]

    syrup.encryptor:
        class: Keboola\ObjectEncryptor\Legacy\Encryptor
        arguments: ["%encryption_key%"]

    syrup.elasticsearch.client:
        class: Elasticsearch\Client
        arguments: ["%elasticsearch%"]

    syrup.elasticsearch.current_component_index:
        class: Keboola\Syrup\Elasticsearch\ComponentIndex
        arguments: ["%app_name%", "%elasticsearch.index_prefix%", "@syrup.elasticsearch.client", "@logger"]

    syrup.elasticsearch.current_component_job_mapper:
        class: Keboola\Syrup\Elasticsearch\JobMapper
        arguments:
          - "@syrup.elasticsearch.client"
          - "@syrup.elasticsearch.current_component_index"
          - "@syrup.object_encryptor_factory"
          - "@logger"
          - "%kernel.root_dir%"

    syrup.elasticsearch.search:
        class: Keboola\Syrup\Elasticsearch\Search
        arguments: ["@syrup.elasticsearch.client", "%elasticsearch.index_prefix%", "@syrup.object_encryptor_factory", "@logger"]

    syrup.queue_factory:
        class: Keboola\Syrup\Service\Queue\QueueFactory
        arguments: ["@doctrine.dbal.syrup_connection", "%queue%", "%app_name%"]

    syrup.job_factory:
        class: Keboola\Syrup\Job\Metadata\JobFactory
        arguments: ["%app_name%", "@syrup.object_encryptor_factory", "@syrup.storage_api"]

    syrup.job_executor:
        class: Keboola\Syrup\Job\Executor

    syrup.job_executor_factory:
        class: Keboola\Syrup\Job\ExecutorFactory
        arguments: ["@syrup.storage_api", "@syrup.job_executor"]

    syrup.object_encryptor_factory:
        class: Keboola\ObjectEncryptor\ObjectEncryptorFactory
        arguments: [null, "%encryption_key%", "%encryption_key%", null, null]
